In [2]:
from timeit import default_timer as timer
import numpy as np
import pandas as pd

dataset_path = '/kaggle/input/intern-data/intern_task.csv'

In [6]:
main_data = pd.read_csv(dataset_path)
main_data

rank  query_id  feature_0  feature_1  feature_2  feature_3  feature_4  \
0          0        10        1.0        0.0        1.0        3.0        3.0   
1          1        10        3.0        0.0        3.0        0.0        3.0   
2          0        10        3.0        0.0        2.0        0.0        3.0   
3          1        10        3.0        0.0        3.0        0.0        3.0   
4          2        10        3.0        0.0        3.0        1.0        3.0   
...      ...       ...        ...        ...        ...        ...        ...   
235253     2     29995        1.0        0.0        0.0        0.0        1.0   
235254     2     29995        1.0        0.0        1.0        0.0        1.0   
235255     1     29995        1.0        0.0        0.0        0.0        1.0   
235256     2     29995        0.0        0.0        0.0        0.0        0.0   
235257     1     29995        0.0        0.0        0.0        0.0        0.0   

        feature_5  feature_6  feature_7  ...  feature_134  feature_135  \
0        0.333333        0.0   0.333333  ...          0.0     0.000000   
1        1.000000        0.0   1.000000  ...          0.0     0.000000   
2        1.000000        0.0   0.666667  ...          0.0     0.000000   
3        1.000000        0.0   1.000000  ...          0.0     0.000000   
4        1.000000        0.0   1.000000  ...        273.0    79.670665   
...           ...        ...        ...  ...          ...          ...   
235253   0.500000        0.0   0.000000  ...          0.0     0.000000   
235254   0.500000        0.0   0.500000  ...          0.0     0.000000   
235255   0.500000        0.0   0.000000  ...          0.0     0.000000   
235256   0.000000        0.0   0.000000  ...          0.0     0.000000   
235257   0.000000        0.0   0.000000  ...          0.0     0.000000   

        feature_136  feature_137  feature_138  feature_139  feature_140  \
0          0.454545     0.890238     8.655534     1.000000     0.077778   
1          0.000000     0.773976    23.130514     0.000000     0.027826   
2          0.000000     0.918308    13.351339     0.000000     0.014925   
3          0.000000     0.975355    18.240926     0.000000     0.053140   
4          0.200000     0.990119    31.786048     0.333333     0.046512   
...             ...          ...          ...          ...          ...   
235253     0.000000     0.471409     0.000000     0.000000     0.001350   
235254     0.000000     0.471409    39.908056     0.000000     0.004850   
235255     0.000000     0.471409     0.000000     0.000000     0.001064   
235256     0.000000     0.000000     0.000000     0.000000     0.000000   
235257     0.000000     0.000000     0.000000     0.000000     0.000000   

        feature_141  feature_142  feature_143  
0          0.002222          1.0     0.333333  
1          0.000430         44.0    14.666667  
2          0.000104         22.0     7.333333  
3          0.000255          8.0     2.666667  
4          0.000307         24.0     8.000000  
...             ...          ...          ...  
235253     0.000002          3.0     1.500000  
235254     0.000014          9.0     4.500000  
235255     0.000001          1.0     0.500000  
235256     0.000000          0.0     0.000000  
235257     0.000000          0.0     0.000000  

[235258 rows x 146 columns]

Разделим датасет на 3 выборки. На валидацию и тест отнесем примерно по 20 процентов запросов.

In [7]:
quids = main_data['query_id'].unique()

In [8]:
len(quids)

2000

In [9]:
first_sep = quids[round(len(quids)*0.6)]
first_sep

18010

In [10]:
second_sep = quids[round(len(quids)*0.8)]
second_sep

24010

In [11]:
train = main_data[main_data['query_id'] < first_sep]
val = main_data[(first_sep <= main_data['query_id']) & (main_data['query_id'] < second_sep)]
test = main_data[second_sep <= main_data['query_id']]

In [12]:
train

rank  query_id  feature_0  feature_1  feature_2  feature_3  feature_4  \
0          0        10        1.0        0.0        1.0        3.0        3.0   
1          1        10        3.0        0.0        3.0        0.0        3.0   
2          0        10        3.0        0.0        2.0        0.0        3.0   
3          1        10        3.0        0.0        3.0        0.0        3.0   
4          2        10        3.0        0.0        3.0        1.0        3.0   
...      ...       ...        ...        ...        ...        ...        ...   
143936     0     17995        0.0        0.0        0.0        2.0        2.0   
143937     0     17995        0.0        0.0        0.0        0.0        0.0   
143938     1     17995        2.0        0.0        2.0        1.0        2.0   
143939     0     17995        2.0        0.0        2.0        2.0        2.0   
143940     0     17995        2.0        0.0        2.0        1.0        2.0   

        feature_5  feature_6  feature_7  ...  feature_134  feature_135  \
0        0.333333        0.0   0.333333  ...          0.0     0.000000   
1        1.000000        0.0   1.000000  ...          0.0     0.000000   
2        1.000000        0.0   0.666667  ...          0.0     0.000000   
3        1.000000        0.0   1.000000  ...          0.0     0.000000   
4        1.000000        0.0   1.000000  ...        273.0    79.670665   
...           ...        ...        ...  ...          ...          ...   
143936   0.000000        0.0   0.000000  ...          0.0     0.000000   
143937   0.000000        0.0   0.000000  ...          0.0     0.000000   
143938   1.000000        0.0   1.000000  ...          0.0     0.000000   
143939   1.000000        0.0   1.000000  ...          0.0     0.000000   
143940   1.000000        0.0   1.000000  ...          0.0     0.000000   

        feature_136  feature_137  feature_138  feature_139  feature_140  \
0          0.454545     0.890238     8.655534     1.000000     0.077778   
1          0.000000     0.773976    23.130514     0.000000     0.027826   
2          0.000000     0.918308    13.351339     0.000000     0.014925   
3          0.000000     0.975355    18.240926     0.000000     0.053140   
4          0.200000     0.990119    31.786048     0.333333     0.046512   
...             ...          ...          ...          ...          ...   
143936     0.153846     0.000000     0.000000     1.000000     0.002786   
143937     0.000000     0.000000     0.000000     0.000000     0.000000   
143938     0.111111     1.000000    27.835708     0.500000     0.027094   
143939     0.200000     0.991224    27.835708     1.000000     0.022333   
143940     0.111111     1.000000    27.835708     0.500000     0.007886   

        feature_141  feature_142  feature_143  
0          0.002222          1.0     0.333333  
1          0.000430         44.0    14.666667  
2          0.000104         22.0     7.333333  
3          0.000255          8.0     2.666667  
4          0.000307         24.0     8.000000  
...             ...          ...          ...  
143936     0.000000          0.0     0.000000  
143937     0.000000          0.0     0.000000  
143938     0.000000         30.0    15.000000  
143939     0.000007         14.0     7.000000  
143940     0.000000          2.0     1.000000  

[143941 rows x 146 columns]

In [13]:
val

rank  query_id  feature_0  feature_1  feature_2  feature_3  feature_4  \
143941     1     18010        2.0        0.0        2.0        1.0        2.0   
143942     1     18010        2.0        0.0        2.0        0.0        2.0   
143943     0     18010        2.0        0.0        2.0        1.0        2.0   
143944     0     18010        2.0        0.0        2.0        1.0        2.0   
143945     2     18010        2.0        0.0        2.0        1.0        2.0   
...      ...       ...        ...        ...        ...        ...        ...   
198155     2     23995        3.0        3.0        3.0        0.0        3.0   
198156     1     23995        3.0        0.0        2.0        0.0        3.0   
198157     0     23995        3.0        1.0        2.0        1.0        3.0   
198158     0     23995        3.0        3.0        3.0        3.0        3.0   
198159     1     23995        3.0        0.0        2.0        2.0        3.0   

        feature_5  feature_6  feature_7  ...  feature_134  feature_135  \
143941        1.0   0.000000   1.000000  ...          0.0          0.0   
143942        1.0   0.000000   1.000000  ...          0.0          0.0   
143943        1.0   0.000000   1.000000  ...          0.0          0.0   
143944        1.0   0.000000   1.000000  ...          0.0          0.0   
143945        1.0   0.000000   1.000000  ...          0.0          0.0   
...           ...        ...        ...  ...          ...          ...   
198155        1.0   1.000000   1.000000  ...          0.0          0.0   
198156        1.0   0.000000   0.666667  ...          0.0          0.0   
198157        1.0   0.333333   0.666667  ...          0.0          0.0   
198158        1.0   1.000000   1.000000  ...          0.0          0.0   
198159        1.0   0.000000   0.666667  ...          0.0          0.0   

        feature_136  feature_137  feature_138  feature_139  feature_140  \
143941     0.111111     0.996212    31.770786     0.500000     0.058036   
143942     0.000000     0.997534    20.005554     0.000000     0.014797   
143943     0.181818     0.875081    40.011107     0.500000     0.073171   
143944     0.166667     0.954119    20.005554     0.500000     0.059091   
143945     0.181818     0.971592    40.011107     0.500000     0.072650   
...             ...          ...          ...          ...          ...   
198155     0.000000     1.000000    17.985703     0.000000     0.008787   
198156     0.000000     0.675582    10.379662     0.000000     0.023293   
198157     0.100000     0.891748    10.379662     0.333333     0.009378   
198158     0.230769     0.986125    17.985703     1.000000     0.026897   
198159     0.250000     0.673853    10.379662     0.666667     0.023375   

        feature_141  feature_142  feature_143  
143941     0.000027          9.0     4.500000  
143942     0.000002         22.0    11.000000  
143943     0.000816         12.0     6.000000  
143944     0.000255          9.0     4.500000  
143945     0.000234         11.0     5.500000  
...             ...          ...          ...  
198155     0.000000          9.0     3.000000  
198156     0.000225        143.0    47.666667  
198157     0.000024         18.0     6.000000  
198158     0.000009         19.0     6.333333  
198159     0.000222        146.0    48.666667  

[54219 rows x 146 columns]

In [14]:
test

rank  query_id  feature_0  feature_1  feature_2  feature_3  feature_4  \
198160     0     24010        3.0        2.0        2.0        0.0        3.0   
198161     1     24010        2.0        0.0        2.0        2.0        2.0   
198162     1     24010        2.0        0.0        1.0        1.0        2.0   
198163     0     24010        3.0        2.0        2.0        0.0        3.0   
198164     0     24010        3.0        1.0        0.0        0.0        3.0   
...      ...       ...        ...        ...        ...        ...        ...   
235253     2     29995        1.0        0.0        0.0        0.0        1.0   
235254     2     29995        1.0        0.0        1.0        0.0        1.0   
235255     1     29995        1.0        0.0        0.0        0.0        1.0   
235256     2     29995        0.0        0.0        0.0        0.0        0.0   
235257     1     29995        0.0        0.0        0.0        0.0        0.0   

        feature_5  feature_6  feature_7  ...  feature_134  feature_135  \
198160   1.000000   0.666667   0.666667  ...          0.0          0.0   
198161   0.666667   0.000000   0.666667  ...          0.0          0.0   
198162   0.666667   0.000000   0.333333  ...          0.0          0.0   
198163   1.000000   0.666667   0.666667  ...          0.0          0.0   
198164   1.000000   0.333333   0.000000  ...          3.0         29.9   
...           ...        ...        ...  ...          ...          ...   
235253   0.500000   0.000000   0.000000  ...          0.0          0.0   
235254   0.500000   0.000000   0.500000  ...          0.0          0.0   
235255   0.500000   0.000000   0.000000  ...          0.0          0.0   
235256   0.000000   0.000000   0.000000  ...          0.0          0.0   
235257   0.000000   0.000000   0.000000  ...          0.0          0.0   

        feature_136  feature_137  feature_138  feature_139  feature_140  \
198160     0.000000     0.805907    16.473262     0.000000     0.013168   
198161     0.222222     0.776164    39.768988     0.666667     0.027168   
198162     0.100000     0.779020     6.822464     0.333333     0.009606   
198163     0.000000     0.824919    26.124061     0.000000     0.015705   
198164     0.000000     0.740175     0.000000     0.000000     0.004230   
...             ...          ...          ...          ...          ...   
235253     0.000000     0.471409     0.000000     0.000000     0.001350   
235254     0.000000     0.471409    39.908056     0.000000     0.004850   
235255     0.000000     0.471409     0.000000     0.000000     0.001064   
235256     0.000000     0.000000     0.000000     0.000000     0.000000   
235257     0.000000     0.000000     0.000000     0.000000     0.000000   

        feature_141  feature_142  feature_143  
198160     0.000073         31.0    10.333333  
198161     0.000278         19.0     6.333333  
198162     0.000041          8.0     2.666667  
198163     0.000088         35.0    11.666667  
198164     0.000019         56.0    18.666667  
...             ...          ...          ...  
235253     0.000002          3.0     1.500000  
235254     0.000014          9.0     4.500000  
235255     0.000001          1.0     0.500000  
235256     0.000000          0.0     0.000000  
235257     0.000000          0.0     0.000000  

[37098 rows x 146 columns]

Будем считать NDCG, поэтому переведем разметку в интервал [0;1]:

In [15]:
def normalize_(vector: pd.Series) -> np.ndarray:
    max_relevance = np.max(vector)
    return (vector / max_relevance).values

Удалим разметку из тестовой части:

In [16]:
y_true = test['rank']
test.drop(['rank'], axis=1, inplace=True)

/tmp/ipykernel_34/1129453403.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test.drop(['rank'], axis=1, inplace=True)


Будем обучать Catboost, а для подбора параметров воспользуемся hyperopt:

In [17]:
!pip install hyperopt==0.2.5

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 966.0/966.0 kB 11.4 MB/s eta 0:00:0000:010:01
  Attempting uninstall: hyperopt
    Found existing installation: hyperopt 0.2.7
    Uninstalling hyperopt-0.2.7:
      Successfully uninstalled hyperopt-0.2.7


Для удобства оформим всё в виде отдельного класса:

In [60]:
from catboost import CatBoostRanker, Pool, utils
import hyperopt
from numpy.random import RandomState

class Model:
    def __init__(self):
        self.best = None
    
    def hyperopt_objective(self, params):
        '''
        Функция, которую будет оптимизировать hyperopt
        '''
        print(params)
        model = CatBoostRanker(
            **params,
            random_seed=42,
            verbose=False,
            task_type='GPU',
            iterations=5000
        )
        model.fit(self.train, eval_set=self.valid)
        score = utils.eval_metric(self.valid.get_label(), model.predict(self.valid), 
                                  'NDCG:top=5;type=Exp', group_id=self.valid.get_group_id_hash())[0]
        return 1 - score

    @staticmethod
    def normalize_(vector: pd.Series) -> pd.Series:
        '''
        Будем считать NDCG, поэтому переведем разметку в интервал [0;1] с помощью этого метода
        '''
        max_relevance = np.max(vector)
        return vector / max_relevance

    def params_optimize(self, df_train, df_valid, method):
        '''
        Метод для подбора параметров
        '''
        y_train = Model.normalize_(df_train['rank'])
        y_valid = Model.normalize_(df_valid['rank'])
        df_train_proc = df_train.drop(['rank', 'query_id'], axis=1)
        df_valid_proc = df_valid.drop(['rank', 'query_id'], axis=1)

        queries_train = df_train['query_id'].astype('Int32')
        queries_test = df_valid['query_id'].astype('Int32')

        train = Pool(
            data=df_train_proc,
            label=y_train,
            group_id=queries_train
        )

        test = Pool(
            data=df_valid_proc,
            label=y_valid,
            group_id=queries_test
        )

        self.train = train
        self.valid = test
        #сетка выбрана на основе https://github.com/catboost/benchmarks/blob/master/ranking/Readme.md
        params_space = {
            'learning_rate': hyperopt.hp.uniform('learning_rate', 0.01, 0.3),
            'depth': hyperopt.hp.quniform('depth', 4, 12, 1),
            'l2_leaf_reg': hyperopt.hp.uniform('l2_leaf_reg', 1, 20),
            'bagging_temperature': hyperopt.hp.uniform('bagging_temperature', 0.8, 1.2),
            'eval_metric': 'NDCG:top=10;type=Exp',
            'loss_function': 'YetiRank',
            'grow_policy': hyperopt.hp.choice('grow_policy', ['Depthwise', 'SymmetricTree', 'Lossguide']),
            'min_data_in_leaf': hyperopt.hp.quniform('min_data_in_leaf', 50, 100, 1),
            'max_bin': hyperopt.hp.quniform('max_bin', 64, 254, 1)
        }

        trials = hyperopt.Trials()
        
        best = hyperopt.fmin(
            self.hyperopt_objective,
            space=params_space,
            algo=method,
            max_evals=60,
            trials=trials,
            rstate=RandomState(42)            
        )
        self.best = best
        self.best['grow_policy'] = ['Depthwise', 'SymmetricTree', 'Lossguide'][self.best['grow_policy']]
        return self.best

    def fit(self, df_train, df_valid, device='CPU'):
        '''
        Итоговое обучение модели. Параметры подхватываются из атрибута best, если заранее были подобраны.
        '''
        y_train = Model.normalize_(df_train['rank'])
        y_valid = Model.normalize_(df_valid['rank'])
        df_train_proc = df_train.drop(['rank', 'query_id'], axis=1)
        df_valid_proc = df_valid.drop(['rank', 'query_id'], axis=1)

        queries_train = df_train['query_id'].astype('Int32')
        queries_test = df_valid['query_id'].astype('Int32')

        train = Pool(
            data=df_train_proc,
            label=y_train,
            group_id=queries_train,
        )

        test = Pool(
            data=df_valid_proc,
            label=y_valid,
            group_id=queries_test
        )

        self.train = train
        self.valid = test

        if self.best:
            self.model = CatBoostRanker(
                **self.best,
                eval_metric='NDCG:top=5;type=Exp',
                random_seed=42,
                verbose=False,
                loss_function='YetiRank',
                iterations=15000, #берём с запасом, в конце возьмем модель с лучшей метрикой на валидации
                use_best_model=True,
                task_type=device
            )
        else:
            print('Используем параметры по умолчанию')
            self.model = CatBoostRanker(
                eval_metric='NDCG:top=5;type=Exp',
                random_seed=42,
                verbose=False,
                loss_function='YetiRank',
                iterations=15000, #берём с запасом, в конце возьмем модель с лучшей метрикой на валидации
                use_best_model=True
            )

        self.model.fit(train, eval_set=test, plot=True)


    def predict(self, df_test):
        return self.model.predict(df_test)

Подберем параметры. Делать это будем на GPU, потому что так сильно быстрее. Прогоним 60 итераций оптимизации по 5000 итераций бустинга в каждой. Будем использовать Байесовский метод оптимизации:

In [43]:
model = Model()

opt_params = model.params_optimize(train, val, hyperopt.tpe.suggest)
opt_params

{'bagging_temperature': 1.0045605546606369, 'depth': 10.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 7.069497769755579, 'learning_rate': 0.03002488885334522, 'loss_function': 'YetiRank', 'max_bin': 222.0, 'min_data_in_leaf': 73.0}
  0%|          | 0/60 [00:00<?, ?trial/s, best loss=?]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.1898703853813748, 'depth': 4.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Lossguide', 'l2_leaf_reg': 7.000192276253925, 'learning_rate': 0.28053171966587176, 'loss_function': 'YetiRank', 'max_bin': 202.0, 'min_data_in_leaf': 71.0}
  2%|▏         | 1/60 [02:25<2:23:16, 145.70s/trial, best loss: 0.4472804172870696]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9380358700105802, 'depth': 8.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 19.073254225273256, 'learning_rate': 0.09798893186641072, 'loss_function': 'YetiRank', 'max_bin': 232.0, 'min_data_in_leaf': 92.0}
  3%|▎         | 2/60 [03:20<1:28:58, 92.04s/trial, best loss: 0.44070925622328316]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0546740494714753, 'depth': 10.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Lossguide', 'l2_leaf_reg': 9.233323235534275, 'learning_rate': 0.04040915598028403, 'loss_function': 'YetiRank', 'max_bin': 239.0, 'min_data_in_leaf': 72.0}
  5%|▌         | 3/60 [04:52<1:27:44, 92.35s/trial, best loss: 0.44070925622328316]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.1023202131343526, 'depth': 5.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 16.252530841969897, 'learning_rate': 0.1834336524785171, 'loss_function': 'YetiRank', 'max_bin': 97.0, 'min_data_in_leaf': 91.0}
  7%|▋         | 4/60 [06:22<1:25:16, 91.36s/trial, best loss: 0.44070925622328316]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.8055591506486478, 'depth': 9.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 14.598551980033625, 'learning_rate': 0.1627198687670308, 'loss_function': 'YetiRank', 'max_bin': 147.0, 'min_data_in_leaf': 90.0}
  8%|▊         | 5/60 [07:17<1:11:33, 78.07s/trial, best loss: 0.44070925622328316]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.91986291843362, 'depth': 12.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Lossguide', 'l2_leaf_reg': 4.580080543543172, 'learning_rate': 0.057446081805179565, 'loss_function': 'YetiRank', 'max_bin': 242.0, 'min_data_in_leaf': 87.0}
 10%|█         | 6/60 [08:44<1:12:56, 81.05s/trial, best loss: 0.44070925622328316]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.8530542929434106, 'depth': 7.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 17.612180611354695, 'learning_rate': 0.11411665025720712, 'loss_function': 'YetiRank', 'max_bin': 211.0, 'min_data_in_leaf': 81.0}
 12%|█▏        | 7/60 [10:13<1:13:57, 83.73s/trial, best loss: 0.44070925622328316]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0283111210715592, 'depth': 4.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 16.915472304150004, 'learning_rate': 0.15397534404304783, 'loss_function': 'YetiRank', 'max_bin': 239.0, 'min_data_in_leaf': 77.0}
 13%|█▎        | 8/60 [11:16<1:06:53, 77.19s/trial, best loss: 0.44070925622328316]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.8000244203010695, 'depth': 6.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Lossguide', 'l2_leaf_reg': 8.900600664009616, 'learning_rate': 0.2627790592543323, 'loss_function': 'YetiRank', 'max_bin': 197.0, 'min_data_in_leaf': 98.0}
 15%|█▌        | 9/60 [12:02<57:16, 67.39s/trial, best loss: 0.44070925622328316]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.1434212723757007, 'depth': 8.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 5.836530899416852, 'learning_rate': 0.2249719958667279, 'loss_function': 'YetiRank', 'max_bin': 219.0, 'min_data_in_leaf': 50.0}
 17%|█▋        | 10/60 [13:20<58:53, 70.66s/trial, best loss: 0.44070925622328316]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9713963408298325, 'depth': 7.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 10.738634301716285, 'learning_rate': 0.1510890015280304, 'loss_function': 'YetiRank', 'max_bin': 132.0, 'min_data_in_leaf': 94.0}
 18%|█▊        | 11/60 [14:56<1:04:01, 78.40s/trial, best loss: 0.4406795828307566]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.166141093975671, 'depth': 11.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 6.861235202491839, 'learning_rate': 0.28846055139726523, 'loss_function': 'YetiRank', 'max_bin': 122.0, 'min_data_in_leaf': 94.0}
 20%|██        | 12/60 [16:10<1:01:47, 77.23s/trial, best loss: 0.4406795828307566]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0742993833635375, 'depth': 6.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 8.122668457579678, 'learning_rate': 0.2565393164418743, 'loss_function': 'YetiRank', 'max_bin': 67.0, 'min_data_in_leaf': 76.0}
 22%|██▏       | 13/60 [18:30<1:15:22, 96.23s/trial, best loss: 0.4406795828307566]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.1978433696880004, 'depth': 8.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 10.36825362522644, 'learning_rate': 0.07901529305069928, 'loss_function': 'YetiRank', 'max_bin': 239.0, 'min_data_in_leaf': 82.0}
 23%|██▎       | 14/60 [19:31<1:05:33, 85.52s/trial, best loss: 0.4387062855305347]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0729239801492794, 'depth': 7.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 14.953142848351797, 'learning_rate': 0.11710521465117803, 'loss_function': 'YetiRank', 'max_bin': 186.0, 'min_data_in_leaf': 79.0}
 25%|██▌       | 15/60 [21:04<1:05:55, 87.89s/trial, best loss: 0.4387062855305347]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9273767153072479, 'depth': 10.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 18.11945125547877, 'learning_rate': 0.09432096779073676, 'loss_function': 'YetiRank', 'max_bin': 88.0, 'min_data_in_leaf': 76.0}
 27%|██▋       | 16/60 [22:22<1:02:10, 84.79s/trial, best loss: 0.4387062855305347]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0726390214073824, 'depth': 12.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Lossguide', 'l2_leaf_reg': 16.58875763210422, 'learning_rate': 0.1536402311602486, 'loss_function': 'YetiRank', 'max_bin': 193.0, 'min_data_in_leaf': 85.0}
 28%|██▊       | 17/60 [23:54<1:02:14, 86.85s/trial, best loss: 0.4387062855305347]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.1612350811822272, 'depth': 10.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 14.381382870733455, 'learning_rate': 0.2451297444862878, 'loss_function': 'YetiRank', 'max_bin': 196.0, 'min_data_in_leaf': 64.0}
 30%|███       | 18/60 [25:24<1:01:31, 87.90s/trial, best loss: 0.4387062855305347]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0094840242185315, 'depth': 12.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Lossguide', 'l2_leaf_reg': 1.4061684121126823, 'learning_rate': 0.25356607346569743, 'loss_function': 'YetiRank', 'max_bin': 230.0, 'min_data_in_leaf': 70.0}
 32%|███▏      | 19/60 [27:52<1:12:20, 105.86s/trial, best loss: 0.4387062855305347]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.1233801214908017, 'depth': 6.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7594587986654107, 'learning_rate': 0.21221106588769234, 'loss_function': 'YetiRank', 'max_bin': 164.0, 'min_data_in_leaf': 54.0}
 33%|███▎      | 20/60 [29:19<1:06:52, 100.32s/trial, best loss: 0.4387062855305347]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.1147403275958099, 'depth': 5.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 4.139438168606409, 'learning_rate': 0.2183714035697752, 'loss_function': 'YetiRank', 'max_bin': 75.0, 'min_data_in_leaf': 53.0}
 35%|███▌      | 21/60 [30:23<58:08, 89.44s/trial, best loss: 0.4387062855305347]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.105367858015578, 'depth': 5.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 3.536459548563513, 'learning_rate': 0.2048188032227964, 'loss_function': 'YetiRank', 'max_bin': 65.0, 'min_data_in_leaf': 64.0}
 37%|███▋      | 22/60 [31:16<49:44, 78.55s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0528912247132045, 'depth': 5.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 12.648795558208858, 'learning_rate': 0.22855048669190198, 'loss_function': 'YetiRank', 'max_bin': 65.0, 'min_data_in_leaf': 58.0}
 38%|███▊      | 23/60 [32:09<43:41, 70.86s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9664607793396335, 'depth': 6.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 1.4457180302045485, 'learning_rate': 0.2992515811259691, 'loss_function': 'YetiRank', 'max_bin': 84.0, 'min_data_in_leaf': 63.0}
 40%|████      | 24/60 [33:03<39:21, 65.59s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.8776477765115502, 'depth': 4.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 1.1061214659683998, 'learning_rate': 0.2984008185457949, 'loss_function': 'YetiRank', 'max_bin': 88.0, 'min_data_in_leaf': 60.0}
 42%|████▏     | 25/60 [34:02<37:05, 63.60s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9659704226657976, 'depth': 5.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.3209200186735828, 'learning_rate': 0.18546089432309976, 'loss_function': 'YetiRank', 'max_bin': 107.0, 'min_data_in_leaf': 50.0}
 43%|████▎     | 26/60 [34:48<33:10, 58.56s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.8873254714817898, 'depth': 5.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 4.348233329933571, 'learning_rate': 0.19047443905377903, 'loss_function': 'YetiRank', 'max_bin': 111.0, 'min_data_in_leaf': 51.0}
 45%|████▌     | 27/60 [35:41<31:17, 56.89s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9867892363061123, 'depth': 4.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.665685716855208, 'learning_rate': 0.17853511283806175, 'loss_function': 'YetiRank', 'max_bin': 107.0, 'min_data_in_leaf': 56.0}
 47%|████▋     | 28/60 [36:36<29:59, 56.24s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0200094264931032, 'depth': 9.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 5.630825952401624, 'learning_rate': 0.12731378737319882, 'loss_function': 'YetiRank', 'max_bin': 169.0, 'min_data_in_leaf': 53.0}
 48%|████▊     | 29/60 [37:24<27:46, 53.76s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9006790472610561, 'depth': 5.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.2700859633014048, 'learning_rate': 0.13587878529273945, 'loss_function': 'YetiRank', 'max_bin': 142.0, 'min_data_in_leaf': 69.0}
 50%|█████     | 30/60 [39:19<36:01, 72.05s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.8892917750097967, 'depth': 7.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 5.941191423309661, 'learning_rate': 0.13502741522640452, 'loss_function': 'YetiRank', 'max_bin': 146.0, 'min_data_in_leaf': 69.0}
 52%|█████▏    | 31/60 [40:15<32:30, 67.28s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.8243693978079429, 'depth': 4.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 4.173973474249341, 'learning_rate': 0.06664473337604265, 'loss_function': 'YetiRank', 'max_bin': 176.0, 'min_data_in_leaf': 67.0}
 53%|█████▎    | 32/60 [41:31<32:35, 69.84s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.8347147175833151, 'depth': 9.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Lossguide', 'l2_leaf_reg': 11.717888012161547, 'learning_rate': 0.010559781024203518, 'loss_function': 'YetiRank', 'max_bin': 145.0, 'min_data_in_leaf': 60.0}
 55%|█████▌    | 33/60 [42:16<28:03, 62.34s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9436456176039761, 'depth': 6.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 7.229124328164683, 'learning_rate': 0.028976158363441668, 'loss_function': 'YetiRank', 'max_bin': 131.0, 'min_data_in_leaf': 67.0}
 57%|█████▋    | 34/60 [43:43<30:17, 69.89s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.862498127007661, 'depth': 5.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 5.125267858755038, 'learning_rate': 0.27549001478835683, 'loss_function': 'YetiRank', 'max_bin': 79.0, 'min_data_in_leaf': 73.0}
 58%|█████▊    | 35/60 [44:49<28:37, 68.70s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9140776554811464, 'depth': 4.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Lossguide', 'l2_leaf_reg': 7.57562086134901, 'learning_rate': 0.09695235843440934, 'loss_function': 'YetiRank', 'max_bin': 156.0, 'min_data_in_leaf': 60.0}
 60%|██████    | 36/60 [45:41<25:30, 63.79s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0387033196789164, 'depth': 7.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 3.3587022962237607, 'learning_rate': 0.23428142894360318, 'loss_function': 'YetiRank', 'max_bin': 121.0, 'min_data_in_leaf': 73.0}
 62%|██████▏   | 37/60 [46:36<23:21, 60.92s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.173006200318307, 'depth': 6.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 9.157118607892384, 'learning_rate': 0.17462187169357238, 'loss_function': 'YetiRank', 'max_bin': 75.0, 'min_data_in_leaf': 56.0}
 63%|██████▎   | 38/60 [47:30<21:38, 59.04s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.906849781223047, 'depth': 4.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Lossguide', 'l2_leaf_reg': 10.320789229755086, 'learning_rate': 0.20867190358420873, 'loss_function': 'YetiRank', 'max_bin': 97.0, 'min_data_in_leaf': 87.0}
 65%|██████▌   | 39/60 [48:31<20:52, 59.64s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9449004251430523, 'depth': 8.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 1.8050342970561193, 'learning_rate': 0.14568343122812882, 'loss_function': 'YetiRank', 'max_bin': 209.0, 'min_data_in_leaf': 66.0}
 67%|██████▋   | 40/60 [49:22<19:00, 57.02s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9890333684621895, 'depth': 5.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 6.485251960691093, 'learning_rate': 0.16564590247683708, 'loss_function': 'YetiRank', 'max_bin': 133.0, 'min_data_in_leaf': 79.0}
 68%|██████▊   | 41/60 [50:36<19:38, 62.00s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.1375193807439912, 'depth': 11.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 8.239349990733789, 'learning_rate': 0.19380797199073332, 'loss_function': 'YetiRank', 'max_bin': 249.0, 'min_data_in_leaf': 52.0}
 70%|███████   | 42/60 [51:33<18:09, 60.54s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.1063434498816442, 'depth': 7.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 3.6169112558040517, 'learning_rate': 0.1171628343323475, 'loss_function': 'YetiRank', 'max_bin': 182.0, 'min_data_in_leaf': 62.0}
 72%|███████▏  | 43/60 [54:45<28:17, 99.88s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.8284433856607978, 'depth': 9.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 4.882453796905417, 'learning_rate': 0.2709192550309456, 'loss_function': 'YetiRank', 'max_bin': 119.0, 'min_data_in_leaf': 71.0}
 73%|███████▎  | 44/60 [55:47<23:36, 88.51s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.1852750520062991, 'depth': 6.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Lossguide', 'l2_leaf_reg': 19.175539902896666, 'learning_rate': 0.03977471063182614, 'loss_function': 'YetiRank', 'max_bin': 154.0, 'min_data_in_leaf': 84.0}
 75%|███████▌  | 45/60 [57:25<22:53, 91.58s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.8551644712666242, 'depth': 8.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 6.318910795298226, 'learning_rate': 0.07565172429314798, 'loss_function': 'YetiRank', 'max_bin': 98.0, 'min_data_in_leaf': 100.0}
 77%|███████▋  | 46/60 [58:43<20:25, 87.56s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0844680465656347, 'depth': 5.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 13.361182550683186, 'learning_rate': 0.13765118135051427, 'loss_function': 'YetiRank', 'max_bin': 139.0, 'min_data_in_leaf': 89.0}
 78%|███████▊  | 47/60 [1:00:04<18:31, 85.53s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.8024972842516757, 'depth': 11.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 9.58572609594169, 'learning_rate': 0.1657111875547558, 'loss_function': 'YetiRank', 'max_bin': 113.0, 'min_data_in_leaf': 74.0}
 80%|████████  | 48/60 [1:01:02<15:25, 77.16s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0399501135093165, 'depth': 6.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Lossguide', 'l2_leaf_reg': 11.555691107264963, 'learning_rate': 0.21771850061560052, 'loss_function': 'YetiRank', 'max_bin': 219.0, 'min_data_in_leaf': 55.0}
 82%|████████▏ | 49/60 [1:03:20<17:29, 95.37s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0053987502701716, 'depth': 7.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 8.405635570090901, 'learning_rate': 0.24410131987570077, 'loss_function': 'YetiRank', 'max_bin': 206.0, 'min_data_in_leaf': 94.0}
 83%|████████▎ | 50/60 [1:04:37<14:59, 89.98s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.1411840786235634, 'depth': 4.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 1.9005928785940243, 'learning_rate': 0.05626051412303129, 'loss_function': 'YetiRank', 'max_bin': 172.0, 'min_data_in_leaf': 78.0}
 85%|████████▌ | 51/60 [1:05:53<12:51, 85.72s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9301874688575864, 'depth': 5.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 5.426008890094021, 'learning_rate': 0.1113299291724236, 'loss_function': 'YetiRank', 'max_bin': 71.0, 'min_data_in_leaf': 81.0}
 87%|████████▋ | 52/60 [1:06:44<10:03, 75.46s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9578675667447334, 'depth': 8.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 3.269675149029069, 'learning_rate': 0.1975334947669428, 'loss_function': 'YetiRank', 'max_bin': 162.0, 'min_data_in_leaf': 58.0}
 88%|████████▊ | 53/60 [1:07:30<07:44, 66.40s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0921989376268042, 'depth': 6.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Lossguide', 'l2_leaf_reg': 19.80441567872547, 'learning_rate': 0.28700282997257287, 'loss_function': 'YetiRank', 'max_bin': 97.0, 'min_data_in_leaf': 69.0}
 90%|█████████ | 54/60 [1:08:59<07:19, 73.27s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9817781826449283, 'depth': 10.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 7.614511703941217, 'learning_rate': 0.15753289605061127, 'loss_function': 'YetiRank', 'max_bin': 227.0, 'min_data_in_leaf': 65.0}
 92%|█████████▏| 55/60 [1:10:10<06:03, 72.66s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.1198587862386757, 'depth': 4.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 15.229381884587607, 'learning_rate': 0.08809543229333332, 'loss_function': 'YetiRank', 'max_bin': 126.0, 'min_data_in_leaf': 96.0}
 93%|█████████▎| 56/60 [1:12:30<06:11, 92.85s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 0.9057992417783842, 'depth': 7.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 4.145717871332755, 'learning_rate': 0.26181594546868986, 'loss_function': 'YetiRank', 'max_bin': 91.0, 'min_data_in_leaf': 62.0}
 95%|█████████▌| 57/60 [1:13:19<03:59, 79.70s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.0509505552586014, 'depth': 5.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 1.0151920869606517, 'learning_rate': 0.10645690824398452, 'loss_function': 'YetiRank', 'max_bin': 191.0, 'min_data_in_leaf': 75.0}
 97%|█████████▋| 58/60 [1:14:30<02:33, 76.93s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



{'bagging_temperature': 1.1973737548392895, 'depth': 4.0, 'eval_metric': 'NDCG:top=10;type=Exp', 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.4788550219485272, 'learning_rate': 0.12453649697061611, 'loss_function': 'YetiRank', 'max_bin': 81.0, 'min_data_in_leaf': 92.0}
 98%|█████████▊| 59/60 [1:15:19<01:08, 68.72s/trial, best loss: 0.4356587409209951]

Default metric period is 5 because PFound
, NDCG
 is/are not implemented for GPU

Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

Metric NDCG:top=10;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time



100%|██████████| 60/60 [1:16:07<00:00, 76.13s/trial, best loss: 0.4356587409209951]


{'bagging_temperature': 1.1147403275958099,
 'depth': 5.0,
 'grow_policy': 'Depthwise',
 'l2_leaf_reg': 4.139438168606409,
 'learning_rate': 0.2183714035697752,
 'max_bin': 75.0,
 'min_data_in_leaf': 53.0}

Обучим итоговую модель:

In [44]:

# Fit
start = timer()
model.fit(train, val, device='GPU')
elapsed = timer() - start
print(f"Model fit: elapsed = {elapsed:.3f}")


MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because PFound, NDCG is/are not implemented for GPU
Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time
Metric NDCG:top=5;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time


Model fit: elapsed = 157.799


In [45]:
# Predict
y_hat_test = model.predict(test)
print(f"Predicted: y_hat_test.shape = {y_hat_test.shape}")

Predicted: y_hat_test.shape = (37098,)


In [46]:
def compute_metrics(y_true, y_hat, q):
    # List of metrics to evaluate
    eval_metrics = ['NDCG:top=5;type=Exp', 'NDCG:top=10;type=Exp']
    
    for eval_metric in eval_metrics:
        scores = utils.eval_metric(y_true, y_hat, eval_metric, group_id=q)
    
        # Print scores
        print(f"metric = {eval_metric} score = {scores[0]:.3f}")

# Get test targets and groups
y_test = y_true.to_numpy()
q_test = test['query_id'].to_numpy().astype('uint32')
    
# Compute metrics on test
compute_metrics(y_test, y_hat_test, q_test)

metric = NDCG:top=5;type=Exp score = 0.461
metric = NDCG:top=10;type=Exp score = 0.494


В качестве итогового набора оставим следующий:
```python
{'bagging_temperature': 1.1147403275958099,
 'depth': 5.0,
 'grow_policy': 'Depthwise',
 'l2_leaf_reg': 4.139438168606409,
 'learning_rate': 0.2183714035697752,
 'max_bin': 75.0,
 'min_data_in_leaf': 53.0}
```

Обучим финальную модель с этим набором и сохраним в файл:

In [63]:
params = {'bagging_temperature': 1.1147403275958099,
 'depth': 5.0,
 'grow_policy': 'Depthwise',
 'l2_leaf_reg': 4.139438168606409,
 'learning_rate': 0.2183714035697752,
 'max_bin': 75.0,
 'min_data_in_leaf': 53.0}

model = Model()
model.best = params

start = timer()
model.fit(train, val, device='GPU')
elapsed = timer() - start
print(f"Model fit: elapsed = {elapsed:.3f}")
y_hat_test = model.predict(test)
print(f"Predicted: y_hat_test.shape = {y_hat_test.shape}")

    
# Compute metrics on test
compute_metrics(y_test, y_hat_test, q_test)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because PFound, NDCG is/are not implemented for GPU
Metric PFound is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time
Metric NDCG:top=5;type=Exp is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time


Model fit: elapsed = 158.866
Predicted: y_hat_test.shape = (37098,)
metric = NDCG:top=5;type=Exp score = 0.465
metric = NDCG:top=10;type=Exp score = 0.494


Посмотрим на то, как далеко мы ушли от случайного прогноза по качеству:

In [53]:
class Random_Model:
    def __init__(self):
        pass

    def fit(self, df_train, df_valid):
        pass

    def predict(self, df_test):
        return np.random.rand(len(df_test))

In [54]:
model = Random_Model()

y_hat_test = model.predict(test)
print(f"Predicted: y_hat_test.shape = {y_hat_test.shape}")

    
# Compute metrics on test
compute_metrics(y_test, y_hat_test, q_test)

Predicted: y_hat_test.shape = (37098,)
metric = NDCG:top=5;type=Exp score = 0.226
metric = NDCG:top=10;type=Exp score = 0.264


Итого, метрики нашей модели на тесте:
```
metric = NDCG:top=5;type=Exp score = 0.461
metric = NDCG:top=10;type=Exp score = 0.494
```
Для случайной модели:
```
NDCG:top=5;type=Exp score = 0.226
NDCG:top=10;type=Exp score = 0.264
```
Видим, что модель получилась сильно лучше случайной.

In [65]:
model.model.save_model("catboost_model.cbm")